version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432" # Puerto externo:interno
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistencia de datos

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80" # Acceso a PgAdmin en el navegador
    depends_on:
      - postgres # Asegura que PostgreSQL esté corriendo antes de iniciar PgAdmin

volumes:
  postgres_data:
